#!/usr/bin/env python

import os
import shutil
from ConfigParser import SafeConfigParser, NoOptionError, NoSectionError

DOC_DIR_REL = os.path.join("docs", "generated")
DOC_DIR_ABS = os.path.join(os.getcwd(), DOC_DIR_REL)


def get_config():
    config = SafeConfigParser()
    config.read(["settings.conf"])
    return config


def get_url_bases():
    config = get_config()

    try:
        github_user = config.get('repo', 'github_user')
    except (NoSectionError, NoOptionError):
        github_user = None

    try:
        github_repo = config.get('repo', 'github_repo')
    except (NoSectionError, NoOptionError):
        github_repo = None

    try:
        pretty_source_url_base = config.get('repo', 'pretty_source_url_format')
    except (NoSectionError, NoOptionError):
        if github_user and github_repo:
            url_format = 'https://github.com/%s/%s/blob/master/%%s'
            pretty_source_url_base = url_format % (github_user, github_repo)
        else:
            pretty_source_url_base = None

    try:
        raw_source_url_base = config.get('repo', 'raw_source_url_format')
    except (NoSectionError, NoOptionError):
        if github_user and github_repo:
            url_format = 'https://raw.githubusercontent.com/%s/%s/master/%%s'
            raw_source_url_base = url_format % (github_user, github_repo)
        else:
            raw_source_url_base = None

    return (pretty_source_url_base, raw_source_url_base)


def remove_files_from_last_run():
    if os.path.isdir(DOC_DIR_ABS):
        shutil.rmtree(DOC_DIR_ABS)


def add_module(modules, file_name, name, args, doc):
    if name.startswith("test"):
        return
    summary, description, doc_args = parse_doc(doc, file_name, name)

    for doc_arg in doc_args.keys():
        if doc_arg not in [arg['name'] for arg in args]:
            msg = 'Documentation for non-existing parameter \'%s\'' % (doc_arg)
            doc_warning(msg, file_name, name)

    for arg in args:
        if arg['name'] not in doc_args:
            msg = 'No documentation for parameter \'%s\'' % (arg['name'])
            doc_warning(msg, file_name, name)
        arg['description'] = doc_args[arg['name']]

    modules[name] = {
        'source': file_name,
        'summary': summary,
        'description': description,
        'args': args,
        }


def doc_warning(msg, file_name, module_name):
    raise RuntimeError('%s -- File %s, module %s' % (
            msg, file_name, module_name))


def parse_block_tags(paragraph, file_name, module_name):
    parameters = {}
    mode = None
    name = None
    value = ''
    for word in paragraph.split(' ') + [None]:
        if word == '':
            pass
        elif word == '@param' or word is None:
            if mode == '@param':
                if name in parameters:
                    msg = 'Parameter \'%s\' occurs more than once in doc' % (
                        name)
                    doc_warning(msg, file_name, module_name)
                if not value:
                    msg = 'Empty documentation for parameter \'%s\'' % (name)
                    doc_warning(msg, file_name, module_name)
                parameters[name] = value
            elif mode is None:
                pass
            else:
                msg = 'Unknown mode \'%s\'' % (word)
                doc_warning(msg, file_name, module_name)
            mode = word
            name = None
            value = ''
        else:
            if mode == '@param':
                if name:
                    if value:
                        value += ' '
                    value += word
                else:
                    name = word
            else:
                msg = 'Unknown mode \'%s\'' % (word)
                doc_warning(msg, file_name, module_name)
    return parameters


def run_command(command):
    return os.system(command)


def render_openscad(scad_file_abs, png_file_abs, file_name, module_name):
    command = "openscad \
        --render \
        --camera=0,0,0,55,0,25,50 \
        --imgsize=512,384 \
        --projection=p \
        -o \"%s\" \
        \"%s\"" % (png_file_abs, scad_file_abs)
    ret = run_command(command)
    if ret == 0:
        if os.path.isfile(png_file_abs):
            if os.path.getsize(png_file_abs) != 0:
                pass
            else:
                msg = 'Render of "%s" produced empty image' % (scad_file_abs)
                doc_warning(msg, file_name, module_name)
        else:
            msg = 'Render of "%s" did not produce image' % (scad_file_abs)
            doc_warning(msg, file_name, module_name)
    else:
        msg = 'Failed to render "%s" (return value: %d)' % (scad_file_abs, ret)
        doc_warning(msg, file_name, module_name)

    return


def parse_openscad_open_tag(line, file_number):
    file_id = None
    line = line.strip()
    attributes = {}
    if line != '<openscad>':
        raw_attribute = ''
        for chunk in (line[:-1] + ' ').split(' ')[1:]:
            if '=' in raw_attribute \
                    and raw_attribute.endswith('"') \
                    and raw_attribute.count('"') >= 2:
                raw_key, raw_value = raw_attribute.split('=', 1)
                raw_value_split = raw_value.split('"')
                attributes[raw_key.strip()] = '"'.join(raw_value_split[1:-1])
                raw_attribute = ''
            if raw_attribute:
                raw_attribute += " "
            raw_attribute += chunk

    file_id = attributes.get('id', 'openscad-%d' % (file_number))
    caption = attributes.get('caption', None)
    alt = attributes.get('alt', file_id)

    return file_id, caption, alt


def parse_openscad(lines, file_number, file_name, module_name):
    while len(lines) >= 3 and not lines[0].strip().endswith('>'):
        lines = [lines[0] + ' ' + lines[1]] + lines[2:]

    file_id, caption, alt = parse_openscad_open_tag(lines[0], file_number)

    media_dir_rel_doc = os.path.join(file_name + '-media')
    media_dir_abs = os.path.join(DOC_DIR_ABS, media_dir_rel_doc)

    scad_file_rel_doc = os.path.join(media_dir_rel_doc, file_id + '.scad')
    scad_file_abs = os.path.join(DOC_DIR_ABS, scad_file_rel_doc)

    png_file_rel_doc = os.path.join(media_dir_rel_doc, file_id + '.png')
    png_file_abs = os.path.join(DOC_DIR_ABS, png_file_rel_doc)

    if not os.path.isdir(media_dir_abs):
        os.makedirs(media_dir_abs)

    with open(scad_file_abs, 'wt') as f:
        f.writelines('\n'.join(lines[1:-1]))

    render_openscad(scad_file_abs, png_file_abs, file_name, module_name)

    markup = '![%s](%s "%s")' % (file_id, png_file_rel_doc, alt)
    if PRETTY_SOURCE_URL_BASE:
        url = PRETTY_SOURCE_URL_BASE % os.path.join(
            DOC_DIR_REL, png_file_rel_doc)
        markup = '[%s](%s)' % (markup, url)

    markup = '| %s |\n| :---: |\n|' % (markup)

    markup += 'Example %d' % (file_number)
    if caption:
        markup += ': %s' % (caption)
    markup += ' '

    if PRETTY_SOURCE_URL_BASE:
        pretty_url = PRETTY_SOURCE_URL_BASE % os.path.join(
            DOC_DIR_REL, scad_file_rel_doc)
    else:
        pretty_url = scad_file_rel_doc
    markup += '[(source)](%s)' % (pretty_url)

    if RAW_SOURCE_URL_BASE:
        raw_url = RAW_SOURCE_URL_BASE % os.path.join(
            DOC_DIR_REL, scad_file_rel_doc)
    else:
        raw_url = scad_file_rel_doc
    markup += '[(raw)](%s)' % (raw_url)

    markup += '|\n'

    return markup


def parse_doc(doc_lines, file_name, module_name):
    summary = None
    description = ''
    parameters = {}
    openscad_count = 0

    foundBlockTags = False
    if doc_lines:
        kind = None
        paragraph = None
        for line in doc_lines + [' *']:
            if line == ' *':
                resetKind = True
                if kind is None:
                    doc_warning('Empty doc chunk', file_name, module_name)
                elif kind == 'text':
                    if paragraph.startswith('<p>'):
                        paragraph = paragraph[4:]
                    if paragraph.endswith('</p>'):
                        paragraph = paragraph[:-4]

                    if not summary:
                        summary = paragraph
                        if not summary.endswith('.'):
                            msg = 'First doc paragraph does not end in \'.\''
                            doc_warning(msg, file_name, module_name)

                    if description:
                        description += '\n'
                    description += '\n%s\n' % (paragraph)
                elif kind == 'block-tags':
                    parameters = parse_block_tags(paragraph, file_name,
                                                  module_name)
                elif kind == 'openscad':
                    if paragraph[-1].strip() == '</openscad>':
                        openscad_count += 1
                        markup = parse_openscad(paragraph, openscad_count,
                                                file_name, module_name)
                        description += '\n%s\n' % (markup)
                    else:
                        paragraph.append('')
                        resetKind = False
                else:
                    msg = 'Unknown paragraph kind \'%s\'' % (kind)
                    doc_warning(msg, file_name, module_name)

                if resetKind:
                    kind = None
                    paragraph = None
            else:
                if not line.startswith(' * '):
                    msg = 'Line \'%s\' does not start in \' * \'' % (line)
                    doc_warning(msg, file_name, module_name)
                line = line[3:]
                if kind is None:
                    if line.startswith('@param'):
                        kind = 'block-tags'
                        if foundBlockTags:
                            msg = 'Line \'%s\' starts second ' + \
                                'block-tags chunk in \' * \'' % (line)
                            doc_warning(msg, file_name, module_name)
                        foundBlockTags = True
                        paragraph = line
                    elif line.startswith('<openscad>') \
                            or line.startswith('<openscad '):
                        kind = 'openscad'
                        paragraph = [line]
                    else:
                        kind = 'text'
                        paragraph = line
                elif kind == 'text':
                    if paragraph:
                        paragraph += ' '
                    paragraph += line
                elif kind == 'block-tags':
                    if paragraph:
                        paragraph += ' '
                    paragraph += line
                elif kind == 'openscad':
                    paragraph.append(line)
                else:
                    msg = 'Unknown paragraph kind \'%s\'' % (kind)
                    doc_warning(msg, file_name, module_name)

    return summary, description, parameters


def parse_arg_unparsed(arg_unparsed):
    to_parse = arg_unparsed.split("(")[1]
    paren_level = 1
    in_string = False
    args = []

    part = ""
    arg_name = ""
    arg_value = ""
    for c in to_parse:
        part += c

        if in_string:
            in_string = (c != '"')
        else:
            parse_arg = False
            if c == '"':
                in_string = True
            elif c in ['(', '[']:
                paren_level += 1
            elif c in [')', ']']:
                paren_level -= 1
                if not paren_level:
                    parse_arg = True
            elif c == '=' and paren_level == 1:
                arg_name = part[:-1].strip()
                part = ""
            elif c == ',' and paren_level == 1:
                parse_arg = True

            if parse_arg:
                arg_value = part[:-1].strip()
                if not arg_name:
                    arg_name = arg_value
                    arg_value = "undef"
                if arg_name:
                    args.append({'name': arg_name, 'value': arg_value})
                arg_name = ""
                arg_value = ""
                part = ""

                if not paren_level:
                    break

    ret = None if paren_level else args
    return ret


def parse_source_file(modules, file_name):
    print "Parsing %s ..." % (file_name)

    resetState = True
    with open(file_name, 'rt') as f:
        for line in f:
            if resetState:
                doc = None
                name = None
                args = None
                arg_unparsed = ""
                resetState = False

            if line.startswith("module "):
                name = line.split("(")[0].split(" ")[-1]

            if name:
                arg_unparsed += line.strip()
                args = parse_arg_unparsed(arg_unparsed)
                if args is not None:
                    add_module(modules, file_name, name, args, doc)
                    resetState = True
            else:
                if line == '/**\n':
                    doc = []
                elif line == ' */\n':
                    pass
                elif line.startswith(' *') and doc is not None:
                    doc.append(line[:-1])
                else:
                    resetState = True


def parse_source_files(directory):
    modules = {}
    walk_root = "."
    for root, dirs, files in os.walk(walk_root):
        rel_path = os.path.relpath(root, walk_root)
        if rel_path == ".":
            rel_path = ""

        files.sort()
        for file_name in files:
            if file_name.endswith('.scad'):
                parse_source_file(modules, os.path.join(rel_path, file_name))

        dirs.sort()
        for prune_dir in [
            '.git',
            'docs',
            'test-expectations',
            'test-results',
        ]:
            if prune_dir in dirs:
                dirs.remove(prune_dir)

    return modules


def render_doc(modules):
    if not os.path.isdir(DOC_DIR_ABS):
        os.makedirs(DOC_DIR_ABS)
    for module, conf in modules.iteritems():
        content = []
        content.append('# %s' % (module))
        content.append('')

        if PRETTY_SOURCE_URL_BASE or RAW_SOURCE_URL_BASE:
            sources = 'Source:'
            if PRETTY_SOURCE_URL_BASE:
                pretty_source_url = PRETTY_SOURCE_URL_BASE % (conf['source'])
                sources += ' [%s](%s)' % (conf['source'], pretty_source_url)
            if RAW_SOURCE_URL_BASE:
                raw_source_url = RAW_SOURCE_URL_BASE % (conf['source'])
                sources += ' ([raw](%s))' % (raw_source_url)
            content.append(sources)
            content.append('')

        if conf['summary']:
            content.append(conf['summary'])
            content.append('')

        if conf['description']:
            content.append('* [Description](#description)')
        content.append('* [Arguments](#arguments)')
        content.append('')

        if conf['description']:
            content.append('## Description')
            content.append('')
            content.append(conf['description'])
            content.append('')

        content.append('## Arguments')
        content.append('')
        content.append('<table>')
        header = '<tr><th>Position</th><th>Name</th><th>Default</th>' + \
            '<th>Description</th></tr>'
        content.append(header)
        position = 1
        for arg in conf['args']:
            row_format = '<tr><td>%d</td><td><code>%s</code></td>' + \
                '<td><code>%s</code></td><td>%s</td></tr>'
            row = row_format % (position, arg['name'], arg['value'],
                                arg['description'])
            content.append(row)
            position += 1
        content.append('</table>')
        content.append('')

        file_name = os.path.join(DOC_DIR_ABS, module) + '.md'
        with open(file_name, 'wt') as f:
            f.writelines('\n'.join(content))


PRETTY_SOURCE_URL_BASE, RAW_SOURCE_URL_BASE = get_url_bases()


def main():
    remove_files_from_last_run()
    modules = parse_source_files(".")
    render_doc(modules)


if __name__ == "__main__":
    main()
